### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'testEnvironmentOptions')

### ISSUE THREAD

**Issue by danid-CB** [kolodny/safetest#12]
FAIL  src/app/app.safetest.tsx
  ● Test suite failed to run

    TypeError: Cannot read properties of undefined (reading 'testEnvironmentOptions')

      at new JSDOMEnvironment (../node_modules/.pnpm/jest-environment-jsdom@29.4.1/node_modules/jest-environment-jsdom/build/index.js:63:28)
      at async TestScheduler.scheduleTests (../node_modules/.pnpm/@jest+core@27.5.1_ts-node@10.9.1/node_modules/@jest/core/build/TestScheduler.js:333:13)
      at async runJest (../node_modules/.pnpm/@jest+core@27.5.1_ts-node@10.9.1/node_modules/@jest/core/build/runJest.js:404:19)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.002 s
Ran all test suites.

Watch Usage: Press w to show more.

Tried both using jsdom and node option in jest.config.ts

**Comment by kolodny** [comment]
What OS are you running? Also did you make sure to run npm install in the root of the project?

**Comment by danid-CB** [comment]
Yes, ran install , macOS 13.6.3

**Comment by kolodny** [comment]
I see you're using `pnpm`, this project uses `npm` for package management within the examples folder. Can you try that?

**Comment by kolodny** [comment]
I added a section in the README for running the [SafeTest examples](https://github.com/kolodny/safetest?tab=readme-ov-file#safetest-development). You should be able to follow it for the angular example, make sure to follow the instructions for installing and running. Closing for now, feel free to reopen if the problem persists.
